name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleFdroid

    - run: ls -l
    - run: ls -l app
    - run: ls -l app/build
    - run: ls -l app/build/outputs
    - run: ls -l app/build/outputs/apk
    - run: ls -l app/build/outputs/apk/fdroid

    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: dialer-fdroid-release.apk
        path: app\build\outputs\apk\fdroid\release\dialer-fdroid-release.apk
